### ISSUE TITLE
 mbedtls/config.h: No such file or directory

### ISSUE THREAD

**Issue by avinash-phaniraj-readify** [Azure/azure-iot-arduino#103]
I also ran into AzureIoTSocket_WiFi library is missing that was reported. Additionally, I ran into compile errors with :

mbedtls/config.h: No such file or directory

I use a generic Arduino Uno board with ESP 8266. 

Any advise will be great.
Thanks,
\A

**Comment by khushvir** [comment]
I am also facing the same issue using NodeMcu

mbedtls/config.h: No such file or directory

Kindly help

**Comment by khushvir** [comment]
Solved...   Just follow the steps.

https://github.com/Azure/azure-iot-arduino#sparkfun-thing-adafruit-feather-huzzah-or-generic-esp8266-board

**Comment by moustafabessar** [comment]
Also it gives me that error  when I run ssl_client.c on vs code
