### ISSUE TITLE
 Calling error callback -- The device client has been disconnected

### ISSUE THREAD

**Issue by khushvir** [Azure/azure-iot-arduino#104]
Creating IoTHub Device handle
 dowork TLSIO_STATE_OPENING_WAITING_DNS
 dowork TLSIO_STATE_OPENING_WAITING_SOCKET
 dowork TLSIO_STATE_OPENING_WAITING_SSL
 -> 09:24:00 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: myiothub.azure-devices.net/mydevice/?api-version=2017-11-08-preview&DeviceClientType=iothubclient%2f1.3.6%20(arduino) | PWD: XXXX | CLEAN: 0
 Received 4 bytes
 <- 09:24:00 CONNACK | SESSION_PRESENT: true | RETURN_CODE: 0x0
 The device client is connected to iothub
 
 -> 09:24:01 SUBSCRIBE | PACKET_ID: 2 | TOPIC_NAME: devices/mydevice/messages/devicebound/# | QOS: 1
 Received 5 bytes
 <- 09:24:01 SUBACK | PACKET_ID: 2 | RETURN_CODE: 1
 Calling error callback
 The device client has been disconnected

Hi, I am getting above error. Disconnecting again and again
I am using ESP8266

**Comment by lfenster** [comment]
was there a response or solution to this?  I am having the same issue
