### ISSUE TITLE
fatal error: undefined reference to IoTHubClient_LL_UploadToBlob_Destroy'` etc

### ISSUE THREAD

**Issue by ForgottenTale** [Azure/azure-iot-arduino#105]
I was Compiling code for nodemcuesp8266 and i got this error 

``C:\Users\abhij\Documents\Arduino\libraries\AzureIoTHub\src\iothub_client_ll_uploadtoblob.c:26:27: fatal error: internal/blob.h: No such file or directory

 #include "internal/blob.h"

                           ^

compilation terminated.

exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module)``

**Comment by khushvir** [comment]
@ForgottenTale have you followed the steps properly 
https://github.com/Azure/azure-iot-arduino#esp8266

I also faced the same issue.

**Comment by ForgottenTale** [comment]
Actually i didn't. Later on after i med 

> @ForgottenTale have you followed the steps properly
> https://github.com/Azure/azure-iot-arduino#esp8266
> 
> I also faced the same issue.

**Comment by ForgottenTale** [comment]
> @ForgottenTale have you followed the steps properly
> https://github.com/Azure/azure-iot-arduino#esp8266
> 
> I also faced the same issue.

Am i getting this error cause i added the `-DDONT_USE_UPLOADTOBLOB -DUSE_BALTIMORE_CERT` to the `platform.txt` improperly ? Also i couldn't find `tlsio_mbedtls.c` is in the `adapters` folder but i couldn't understand where to look for 'tlsio_mbedtls.c' is defined

**Comment by ForgottenTale** [comment]
After i restarted my pc. Its working.
