### ISSUE TITLE
How to Invoke direct methods?

### ISSUE THREAD

**Issue by khushvir** [Azure/azure-iot-arduino#106]
I want to Invoked Direct Methods on my Esp8266. Is it supported? 

Before I was using the below example and direct methods were working fine but in this, it is not working.
https://github.com/Azure-Samples/iot-hub-feather-huzzah-client-app

Did anyone try?

**Comment by jbobotek** [comment]
What do you mean by Direct Methods?

**Comment by khushvir** [comment]
@jbobotek  
here ----- > https://docs.microsoft.com/bs-latn-ba/azure/iot-hub/iot-hub-devguide-direct-methods

**Comment by khushvir** [comment]
solved
