### ISSUE TITLE
what version of the Arduino library is used and which TLS version does this library use?

### ISSUE THREAD

**Issue by designncode7** [Azure/azure-iot-arduino#107]
Since TLS 1.0 and 1.1 are being [deprecated ](https://azure.microsoft.com/en-in/updates/iot-devices-and-applications-to-only-use-tls-12-for-communication-with-iot-hub-and-dsp/) and TLS 1.2 will be used instead - as of July 2020 - we need to find out what TLS version we are using.

I know the latest C SDK does use TLS 1.2.  But if we are already using TLS 1.2, then we do not need to upgrade our devices to the latest C SDK for now.

1>> how can we find out the version number of the Arduino library we are using?
2>> how can we find out the current version of TLS (1.0, 1.1 or 1.2) that our Arduino library is using?

Thanks,
Guss-an Hariz.

**Comment by jbobotek** [comment]
TLS implementation is device specific: For the ESP32, it uses mbedtls. For the ESP8266, it uses BearSSL. Both implementations should have options to force use of TLS 1.2 only. For BearSSL, I know of a function listed here that will force 1.2 on the device side: https://www.bearssl.org/support.html.

**Comment by jbobotek** [comment]
In regards to support for tls 1.2, both do. As for C SDK versions, if you are building from the Manage Libraries release, the version listed there matches the actual SDK version.
