### ISSUE TITLE
Syncing samples from SDK

### ISSUE THREAD

**Issue by sandeepmistry** [Azure/azure-iot-arduino#11]
The `simplesample_http.c` appears to be modified from upstream: https://github.com/Azure/azure-iot-sdks/tree/master/c/serializer/samples/simplesample_http

We should find a way to synchronize this so we can keep up to date with SDK example updates. Also, the `#include "AzureIoT.h"` will need to changed to `#include "AzureIoTHub.h"` upstream.

**Comment by sandeepmistry** [comment]
@stefangordon @obsoleted any thoughts on this?

I used the ```simplesample_http``` example to certify the Arduino Zero + WiFi 101 shield and MKR1000 because the [How to certify IoT devices on Non-Supported Platforms with Azure IoT SDK](https://github.com/Azure/azure-iot-sdks/blob/master/doc/iotcertification/iot_certification_port_c_libraries_other_platforms/iot_certification_port_c_libraries_other_platforms.md) guide mentions "Run and Validate the Samples" in section 3.2.

Questions:
 * Should we keep in it sync or remove?
 * Does it add value as an example? I think it makes it easy for others to certify new boards.
 * What about the [iothub_client_sample_http](https://github.com/Azure/azure-iot-sdks/tree/master/c/iothub_client/samples/iothub_client_sample_http) that was included prior to #1?

**Comment by obsoleted** [comment]
I'll take a look at this. Some of the divergence might have actually been my fault when iterating locally a bit. I think there is value in having it, as you said it is a nice simple sample that helps ensure functionality.

I think we have decent coverage with the samples we have now. And we should probably tackle the unification first before adding more incase there are common patterns we can use.

**Comment by tameraw** [comment]
Infrastructure has changed. We source the code from the new "c" SDK repo.
