### ISSUE TITLE
message delivery stops after network issue

### ISSUE THREAD

**Issue by dineshairjaldi** [Azure/azure-iot-arduino#112]
I am using nodemcu and successfully sending data to azure IoT hub. However if the wifi AP reboots then nodemcu stops sending the messages because IoT hub hasn't accepted the previous message yet. In another case if there are packet loss in the link the same issue occurs.
Can we set a timeout value in case the message is not accepted within the time specified then reinitiate the wifi connection?

**Comment by jbobotek** [comment]
Have you tried building the latest? It includes a fix for some disconnect issues. Latest located here: https://github.com/Azure/azure-iot-pal-arduino
