### ISSUE TITLE
IoT Central example

### ISSUE THREAD

**Issue by rploeg** [Azure/azure-iot-arduino#116]
Hello,

I am trying to find a example for IoT Central. I have found a lot of example, but all based on connection strings and not on the new DPS structure that we need to use in Azure IoT Central. Also this example is based on a connection string.

**Comment by jbobotek** [comment]
You are correct, there is currently no example for these Arduino boards for DPS. There is also not one currently planned for this repo.

**Comment by rploeg** [comment]
Thanks. But will the library every support it? Because connection string will be not supported in the future of IoT Central anymore
