### ISSUE TITLE
Support for Device Provisioning Support

### ISSUE THREAD

**Issue by Tintin4000** [Azure/azure-iot-arduino#119]
Is device provisioning supported by this library?  If so do you have any example or if not, when do you plan to be able to do so?
Would the example from the azure-iot-sdk-c bring me anywhere running on Arduino?

**Comment by jbobotek** [comment]
The sample does not currently support DPS, and there are no current plans to add a DPS sample. However, there are DPS samples in the main repo that you are free to port!: https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_client/samples/prov_dev_client_ll_sample/prov_dev_client_ll_sample.c
