### ISSUE TITLE
DECLARE_MODEL does not name a type

### ISSUE THREAD

**Issue by plasne** [Azure/azure-iot-arduino#21]
If I compile with Arduino v1.6.7 or earlier, everything seems to work fine. But if I compile with Arduino v1.6.8 or later, I get an error on DECLARE_MODEL that the <name> does not name a type.

EX:
BEGIN_NAMESPACE(wfi);
  DECLARE_MODEL(widget,
    WITH_DATA(ascii_char_ptr, DeviceId),
    WITH_DATA(int, Value)
  );
END_NAMESPACE(wfi);

report_to_iothub:16: error: 'widget' does not name a type
   DECLARE_MODEL(widget,
                                                                                             ^
report_to_iothub:16: error: ISO C++ forbids declaration of 'value' with no type [-fpermissive]
   DECLARE_MODEL(widget,

**Comment by plasne** [comment]
Oh, and BTW, you can forward declare the variable, so...
class widget;
...works. I don't know if this is just a change to the sample maybe or there is something that can be done in the source.

**Comment by Endlesshunt** [comment]
Hi, any fix/progress on this issue yet?

**Comment by photomoose** [comment]
I'm getting the same issue. Did anyone manage to resolve it?

**Comment by photomoose** [comment]
For reasons unknown to me, it appears to work if the namespace and model are declared in a separate file (e.g. a header file) rather than the main file containing setup() and loop(). This is also how it is done in the examples.

**Comment by GregTerrell** [comment]
Keep in mind that the INO is C++ the model is C.  So by moving, you selected different compile options.

Greg Terrell
CEO, LooUQ

________________________________

**Comment by photomoose** [comment]
Thanks for confirmation @GregTerrell. Indeed, defining the model in a .cpp file fails, whereas defining it in a .c file works fine. Back to basics for me, it has been years since I've done any C++/C.
