### ISSUE TITLE
When can we have AMQP_Protocol or MQTT_Protocol support?

### ISSUE THREAD

**Issue by yaweiw** [Azure/azure-iot-arduino#26]
as titled.

**Comment by olivierbloch** [comment]
Hi @yaweiw 
This is a perfectly reasonable ask (at least for MQTT as I suspect AMQP might be a bit too much in terms of memory usage to be brought up). We will look into this soon and will keep you posted here.

**Comment by henrik-d** [comment]
Can you please confirm or refute, that currently only sending data to the IoTHub is supported and **not** receiving messages via MQTT? I'm a bit confused...

**Comment by olivierbloch** [comment]
At this point you can only use HTTP to send AND receive messages using the Arduino lib.
We are planning to bring MQTT support soon and certainly AMQP later.

**Comment by henrik-d** [comment]
Hey, thanks for the answer. How can I receive notifications with HTTP? Does your lib use long polling?

**Comment by olivierbloch** [comment]
The library doesn't implement long poling, you have to do it in your  loop. MQTT will definitively solve this.

**Comment by yaweiw** [comment]
For AMQP & MQTT, I use below code snippet to poll for iot client status
               while ((IoTHubClient_LL_GetSendStatus(iotHubClientHandle, &status) == IOTHUB_CLIENT_OK) && (status == IOTHUB_CLIENT_SEND_STATUS_BUSY))
                {
                    IoTHubClient_LL_DoWork(iotHubClientHandle);
                    ThreadAPI_Sleep(100);
                }

**Comment by olivierbloch** [comment]
Hi @yaweiw 
I wouldn't recommend using this pattern. When using the lower layer of the C SDK (you can read more about lower layer vs. convenience layer of the C SDK [here](https://github.com/Azure/azure-content-pr/blob/master/articles/iot-hub/iot-hub-devguide-direct-methods.md)), the DoWork is about triggering all the work the client SDK has to do: send a message, receive a message,...). If you condition the call to DoWork on the GetSendStatus, then you will never receive a message if you are not sending one...

**Comment by yaweiw** [comment]
@olivierbloch in our code, sending is happening constantly.. any possibility to just receive while not send. I guess it's no according to behavior of IoTHubClient_LL_DoWork?

**Comment by olivierbloch** [comment]
Actually you can receive without ever sending. You need to register the callback for receiving messages, then regularly call DoWork. If a message is sent from the Cloud to the device then the next time the DoWork is called, the device client will get the message and will invoke the callback you registered. Our samples show this pattern

**Comment by henrik-d** [comment]
@olivierbloch Could you roughly estimate when you will support MQTT with this library? In 1 month, 6 month or 1 year?

**Comment by mingdee** [comment]
Please I would like to have that answer as well.

**Comment by magohl** [comment]
Would also very much like to know any kind of rough timeline indication on this. Thanks for the great work!

**Comment by olivierbloch** [comment]
We are actively working on bringing MQTT support and expect this to be shipped in the next month or so.

**Comment by spincraft** [comment]
MQTT would make a great Holiday gift!
Thanks for your efforts.
Best regards

**Comment by mamokarz** [comment]
Hi,
Microsoft has just added MQTT for Arduino... Happy holydays!
