### ISSUE TITLE
Ethernet Compatibility

### ISSUE THREAD

**Issue by hvaughan3** [Azure/azure-iot-arduino#28]
Current have an Adafruit Ethernet FeatherWing and installed the Ethernet2 library. Wanted to us that to send data to the Azure IoT Hub. I see that in the simplesample_http sample, the `AzureIoTHubClient` instance expects a `WiFiClientSecure` but wanted to know if there is anyway to pass in an ethernet client of some kind.

I also was not able to find a secure ethernet client so that may be another road block but I have extremely limited knowledge of all of this so I could be mistaken.

**Comment by mamokarz** [comment]
Hi hvaughan3,

You are missing layers on your communication. In a generic form, the IoT Hub communication needs the follow sequence of layers:

5. **Application**: The AzureIoTHubClient creates the information to send to the Hub, for instance, in the remote-monitoring sample, it creates a json with the temperature and humidity. 
4. **HTTP**: It adds a http protocol over the json, for instance, it will send a HTTP POST to the IoT Hub, and check the answer, if this post was accepted or if there was any problem, like access denied. 
3. **Transport**: The transport layer will make sure that the HTTP packet will arrive in the Hub correctly, with all characters, in the right sequence, etc. Besides that, IoT Hub request a security transportation, it means that you must use TLS on your transport layer.
2. **Internet**: The Internet layer will move the datagram generated in the transport layer over different networks around the world. These many networks are what we call Internet.
1. **Ethernet**: The Ethernet layer is responsible for the local communication, only from the Arduino to your Ethernet switch. 

Taking a look at the Ethernet2 library, it probably provides layers 1 and 2 for Arduino. You can use the other layers from the azure-iot-arduino, but, you must figure out how to connect the SSLClient to the Ethernet2 library.

If you have limited experience with protocols, my suggestion is to you start with one of the Microsoft Azure IoT Starter Kits, find more at https://azure.microsoft.com/en-us/develop/iot/starter-kits/.

**Comment by hvaughan3** [comment]
@mamokarz Thanks so much for the information. Very helpful. I will look into the starter kits for now and might come back to the Ethernet2 library when I have time. Appreciate your help.

**Comment by cocosnuss** [comment]
Are there any updates @hvaughan3 ? I have the same problem but can not work with a wireless network (not available). I appreciate any help!
