### ISSUE TITLE
Can we use "azure-iot-arduino" to "M-DUINO PLC Arduino"..????

### ISSUE THREAD

**Issue by Monish-Thatraju** [Azure/azure-iot-arduino#29]
Hello

I want to use **M-DUINO PLC Arduino 19R I/Os Relay / Analog / Digital** for my project (Arduino for AzureIOT). So can anyone let me know if i can use "AzureIoTHub - Azure IoT Hub library for Arduino" to my M-Duino PLC arduino

for more details about PLC arduino, please go through the below link
 [more details about M-DUINO PLC](http://www.industrialshields.com/shop/m-duino-plc-arduino-17r-i-os-relay_analog-digital/)
can you please help me out of this thing.
Thank u

**Comment by mamokarz** [comment]
Hi Manish-Thatraju,

We are glad that you intend to use the Azure IoT on your PLC. 

The answer for your question is yes, there are samples for Arduino ESP6266 and Feather-M0, with the source code. Please take a look at the follow tutorials:

https://azure.microsoft.com/en-us/documentation/samples/iot-hub-c-m0wifi-getstartedkit/
https://azure.microsoft.com/en-us/documentation/samples/iot-hub-c-huzzah-getstartedkit/
https://azure.microsoft.com/en-us/documentation/samples/iot-hub-c-thingdev-getstartedkit/
