### ISSUE TITLE
Compile error In function `strtof' in simplesample_http on ESP8266

### ISSUE THREAD

**Issue by ratnick** [Azure/azure-iot-arduino#31]
When compiling the simplesample_http example, I get the following error:

J:\Programmer\Arduino\hardware\esp8266com\esp8266/tools/sdk/libc/xtensa-lx106-elf/lib\libc.a(lib_a-strtod.o): In function `strtof':

/Users/igrokhotkov/e/newlib-xtensa/xtensa-lx106-elf/newlib/libc/stdlib/../../../.././newlib/libc/stdlib/strtod.c:1267: multiple definition of `strtof'

libraries\azure-iot-arduino-master\esp8266\azcpgmspace.cpp.o:I:\DEV\Arduino\libraries\azure-iot-arduino-master\src\esp8266/azcpgmspace.cpp:24: first defined here

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Generic ESP8266 Module.

I have also tried many other things:
- different boards: Adafruit HUZZAH, Sparkfun ESP8266 Dev,  WeMo D1 and more. Same result.
- Stripping the .ino to bare minimum by removing all includes (and related code). It's the inclusion of the AzureIoTHub.h that spawns the problem.

System:
- Arduino IDE 1.6.12
- esp8266 Community library v 2.3.0
- AzureIOTHub, 1.0.0=master branch (not sure if this is actually expected to be working, but if I install 0.2.0, I get other problems during runtime).
- HW: Arduino WeMo D1 (ESP8266). But not relevant, since I never get through the compiler.

I have removed all other libraries.

What do I do wrong here?

**Comment by ratnick** [comment]
Hi again. I found out. Uninstalled everything and removed old stuff. Then re-installed everything (IDE, libraries, boards). And that seemed to help.

**Comment by aj-ptw** [comment]
I'm having this problem and still cannot solve it after nuking my system.

I opened issue for [Azure/azure-iot-arduino-protocol-mqtt/issues/9](https://github.com/Azure/azure-iot-arduino-protocol-mqtt/issues/9)
