### ISSUE TITLE
SAM3X8E support

### ISSUE THREAD

**Issue by alex-zyl** [Azure/azure-iot-arduino#37]
There is Arduino Due build on SAM3X8E Cortex-M3 which is very similar to Mega 2560 from the number of pins perspective. 
Is is possible to bring the support of this SDK to this platform?

**Comment by olivierbloch** [comment]
Now tracked on [User Voice](https://feedback.azure.com/forums/321918-azure-iot/suggestions/19109230-add-support-for-sam3x8e-cortex-m3-to-the-c-device). Please vote up there if interested. Thanks
