### ISSUE TITLE
How to connect  Arduino to Azure IOT using Ethernet?

### ISSUE THREAD

**Issue by yuvaraj-gimco** [Azure/azure-iot-arduino#38]
I have a requirement to connect Arduino to Azure IOT using Ethernet.  **Azure/Azure-iot-arduino** Package is not compatible with Ethernet.Can any one guide me,how to do this..?

**Comment by astaykov** [comment]
This is duplicate of #28 

Currently there is no direct support for Ethernet.

**Comment by tameraw** [comment]
Please see response in #28.
