### ISSUE TITLE
simplesample_mqtt crash

### ISSUE THREAD

**Issue by mingdee** [Azure/azure-iot-arduino#40]
After upgrading from 1.0.17 to 1.0.21, both simplesample_mqtt and simplesample_http crash at:
...
Connected to wifi
please start sntp first !
Fetching NTP epoch time failed! Waiting 2 seconds to retry.
Mon Jan 23 19:43:57 2017

Fetched NTP epoch time is: 1485200638
Fatal exception 3(LoadStoreErrorCause):
epc1=0x4000bf64, epc2=0x00000000, epc3=0x00000000, excvaddr=0x40251d6b, depc=0x00000000

Exception (3):
epc1=0x4000bf64 epc2=0x00000000 epc3=0x00000000 excvaddr=0x40251d6b depc=0x00000000

ctx: cont 
sp: 3fff3230 end: 3fff3530 offset: 01a0

>>>stack>>>
3fff33d0:  3fff35b8 3fff430c 00000035 401077e0  
3fff33e0:  40105f9f 3fff34c0 3fff34c0 3ffec846  
3fff33f0:  40105ff8 00000000 40001da0 3fff34c0  
3fff3400:  3fff2504 3fff35b8 00000004 000000d2  
3fff3410:  3fff35b8 00000000 00000000 3fff33a0  
3fff3420:  01000100 00000009 3fff348f 4021520c  
3fff3430:  00000000 3ffe8372 3fff2504 3fff24d8  
3fff3440:  00000031 0000000a 3fff24d8 40214b65  
3fff3450:  3fff3486 3fff35cc 3fff35c0 4023f9e8  
3fff3460:  3fff3480 4020652d 00000000 3ffe937c  
3fff3470:  3fffdad0 4defeffe 64676e69 00000000  
3fff3480:  40251d6b 3ffea967 00000000 3fff23c8  
3fff3490:  00000002 ff000000 3ffe92de 4021520c  
3fff34a0:  00000009 0000001a 3ffe9a8f 3fff2504  
3fff34b0:  3fffdad0 0000000a 3fff24d8 40214b65  
3fff34c0:  3ffe92dd 58865cfe 3fff23d0 40203f2c  
3fff34d0:  3ffe9a75 3fff2504 3fff24d8 3fff2504  
3fff34e0:  3fffdad0 00000000 00000000 40201216  
3fff34f0:  3fffdad0 58865cfe 3fff24d8 40213421  
3fff3500:  3fffdad0 00000000 3fff24fc 402132fc  
3fff3510:  feefeffe feefeffe feefeffe 40214ea0  
3fff3520:  feefeffe feefeffe 3fff2510 40100718  
<<<stack<<<

 ets Jan  8 2013,rst cause:1, boot mode:(3,7)

Any idea?

**Comment by mingdee** [comment]
Update: when I disable logging in the library (#define NO_LOGGING), the crash is gone.

**Comment by ufuf** [comment]
@mingdee where exactly did you add no_logging?

**Comment by dnienhis** [comment]
@ufuf did you figure out where to #define NO_LOGGING?   I've got the same error :(

**Comment by mingdee** [comment]
I put a #define NO_LOGGING in very beginning in
~/Documents/Arduino/libraries/AzureIoTUtility/src/azure_c_shared_utility/xlogging.h

../ming

**Comment by dnienhis** [comment]
#Perfect!!!   Mine now works also - thank you much!

**Comment by ufuf** [comment]
Thanks @mingdee I'll try it out too.

**Comment by JetstreamRoySprowl** [comment]
Is this still an issue for you? If so, can you add what hardware you're using and any other relevant repro info?

**Comment by tameraw** [comment]
Please let us know if still an issue.
