### ISSUE TITLE
Getting Azure IoT to work on Sparkfun ESP32 Thing 

### ISSUE THREAD

**Issue by vaishaks** [Azure/azure-iot-arduino#49]
I'm working on an IoT project with the Sparkfun ESP32 Thing. I'm getting the following compile time error.
`/home/vaishaks/Arduino/libraries/WiFi101/src/WiFiMDNSResponder.cpp:24:26: fatal error: avr/pgmspace.h: No such file or directory`

Can someone tell me how I can contribute to support the ESP32 board?

**Comment by zzeekk** [comment]
Hello, azure-iot-arduino-utility library doesn't yet support ESP32, and therefore doesn't include the correct wifi library for ESP32. I created a pull request to fix that: https://github.com/Azure/azure-iot-arduino-utility/pull/1

**Comment by vaishaks** [comment]
Thanks for this!

**Comment by greiginsydney** [comment]
Should I read this to mean that the [Sparkfun ESP32 Thing](https://www.sparkfun.com/products/13907) is now also supported?

**Comment by jbobotek** [comment]
The biggest thing that changes for different board variants with Arduino is just the pin locations, so I imagine the Sparkfun ESP32 should work now with wifi.
