### ISSUE TITLE
Possible bug in, or related to use of, IoTHubClient_LL_SendReportedState()

### ISSUE THREAD

**Issue by zoidicus** [Azure/azure-iot-arduino#56]
I cannot find an example demonstrating use of `IoTHubClient_LL_SendReportedState()` on the ESP8266.  When I try use that function in [an otherwise stable tutorial project](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-arduino-huzzah-esp8266-get-started), the device locks up moments later during a call to `delay(10);`.  I've tried to alter the call sequence and delay durations, but the result is always the same.  Execution freezes inside of delay() and the WDT resets the module after a few seconds.

I attempted to switch the entire project to the non _LL function variants, but they are not included (at least not fully).

**Comment by JetstreamRoySprowl** [comment]
Hi @zoidicus , the non-LL function variants will not work on Arduino because they require threading support that Arduino does not offer.

Can you supply the code where you're calling `IoTHubClient_LL_SendReportedState()` from?
