### ISSUE TITLE
ESP32 Arduino porting...

### ISSUE THREAD

**Issue by mopplayer** [Azure/azure-iot-arduino#58]
I got unreferenced errors:

C:\Users\MOP\AppData\Local\Temp\arduino_build_729655\libraries\AzureIoTUtility\azure_c_shared_utility\httpapiex.c.o:(.literal.HTTPAPIEX_ExecuteRequest+0x3c): undefined reference to `HTTPAPI_Init'

C:\Users\MOP\AppData\Local\Temp\arduino_build_729655\libraries\AzureIoTUtility\azure_c_shared_utility\httpapiex.c.o:(.literal.HTTPAPIEX_ExecuteRequest+0x40): undefined reference to `HTTPAPI_CreateConnection'

C:\Users\MOP\AppData\Local\Temp\arduino_build_729655\libraries\AzureIoTUtility\azure_c_shared_utility\httpapiex.c.o:(.literal.HTTPAPIEX_ExecuteRequest+0x44): undefined reference to `HTTPAPI_SetOption'

C:\Users\MOP\AppData\Local\Temp\arduino_build_729655\libraries\AzureIoTUtility\azure_c_shared_utility\httpapiex.c.o:(.literal.HTTPAPIEX_ExecuteRequest+0x48): undefined reference to `HTTPAPI_ExecuteRequest'

C:\Users\MOP\AppData\Local\Temp\arduino_build_729655\libraries\AzureIoTUtility\azure_c_shared_utility\httpapiex.c.o:(.literal.HTTPAPIEX_ExecuteRequest+0x4c): undefined reference to `HTTPAPI_Deinit'

C:\Users\MOP\AppData\Local\Temp\arduino_build_729655\libraries\AzureIoTUtility\azure_c_shared_utility\httpapiex.c.o:(.literal.HTTPAPIEX_ExecuteRequest+0x50): undefined reference to `HTTPAPI_CloseConnection'

C:\Users\MOP\AppData\Local\Temp\arduino_build_729655\libraries\AzureIoTUtility\azure_c_shared_utility\httpapiex.c.o:(.literal.HTTPAPIEX_SetOption+0x10): undefined reference to `HTTPAPI_CloneOption'

C:\Users\MOP\AppData\Local\Temp\arduino_build_729655\libraries\AzureIoTUtility\azure_c_shared_utility\httpapiex.c.o: In function `HTTPAPIEX_ExecuteRequest':

C:\Users\MOP\Documents\Arduino\libraries\AzureIoTUtility\src\azure_c_shared_utility/httpapiex.c:337: undefined reference to `HTTPAPI_Init'

C:\Users\MOP\Documents\Arduino\libraries\AzureIoTUtility\src\azure_c_shared_utility/httpapiex.c:475: undefined reference to `HTTPAPI_CreateConnection'

C:\Users\MOP\Documents\Arduino\libraries\AzureIoTUtility\src\azure_c_shared_utility/httpapiex.c:385: undefined reference to `HTTPAPI_SetOption'

C:\Users\MOP\Documents\Arduino\libraries\AzureIoTUtility\src\azure_c_shared_utility/httpapiex.c:400: undefined reference to `HTTPAPI_ExecuteRequest'

C:\Users\MOP\Documents\Arduino\libraries\AzureIoTUtility\src\azure_c_shared_utility/httpapiex.c:411: undefined reference to `HTTPAPI_Deinit'

C:\Users\MOP\Documents\Arduino\libraries\AzureIoTUtility\src\azure_c_shared_utility/httpapiex.c:411: undefined reference to `HTTPAPI_CloseConnection'

C:\Users\MOP\AppData\Local\Temp\arduino_build_729655\libraries\AzureIoTUtility\azure_c_shared_utility\httpapiex.c.o: In function `HTTPAPIEX_Destroy':

C:\Users\MOP\Documents\Arduino\libraries\AzureIoTUtility\src\azure_c_shared_utility/httpapiex.c:497: undefined reference to `HTTPAPI_CloseConnection'

C:\Users\MOP\Documents\Arduino\libraries\AzureIoTUtility\src\azure_c_shared_utility/httpapiex.c:432: undefined reference to `HTTPAPI_Deinit'

C:\Users\MOP\AppData\Local\Temp\arduino_build_729655\libraries\AzureIoTUtility\azure_c_shared_utility\httpapiex.c.o: In function `HTTPAPIEX_SetOption':

C:\Users\MOP\Documents\Arduino\libraries\AzureIoTUtility\src\azure_c_shared_utility/httpapiex.c:603: undefined reference to `HTTPAPI_CloneOption'

C:\Users\MOP\Documents\Arduino\libraries\AzureIoTUtility\src\azure_c_shared_utility/httpapiex.c:651: undefined reference to `HTTPAPI_SetOption'

collect2.exe: error: ld returned 1 exit status
where are definitions of those functions?
Thanks a lot.

**Comment by FHFS** [comment]
You are missing [httpapi_compact.c](https://github.com/Azure/azure-c-shared-utility/blob/master/adapters/httpapi_compact.c) I added this manually from this repo.

**Comment by JetstreamRoySprowl** [comment]
@mopplayer : is this issue taken care of for you?
