### ISSUE TITLE
how can i send TurnFanOn and TurnFanOff manually ? 

### ISSUE THREAD

**Issue by MehranMazhar** [Azure/azure-iot-arduino#59]
how can i call methods ( TurnFanOn and TurnFanOff)  using device explorer in windows or azure-cli ? 

![zure](https://user-images.githubusercontent.com/11898578/28835371-5961ef64-76fa-11e7-905a-d0e59c5ce2a9.jpg)

**Comment by MehranMazhar** [comment]
![zure](https://user-images.githubusercontent.com/11898578/28834235-f1541cba-76f6-11e7-80f4-841692dc7e1f.jpg)

**Comment by tameraw** [comment]
@MehranMazhar - Please checkout this document 
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-device-sdk-c-serializer#message-handling

Basically, you want to follow this json format:
If no parameters:
{"Name":"TurnFanOff", "Parameters":{}}
If One Parameter:
{"Name":"SetAirResistance","Parameters":{"Position":42}}
If Multiple Parameters:
{"Name":"SetAirResistance2","Parameters":{"Position1":10, "Position2":20}}

**Comment by tameraw** [comment]
Closing. If still encountering problems, please let us know.

**Comment by MehranMazhar** [comment]
thanks . its worked for me .
