### ISSUE TITLE
Doc improvements : device setup clarifications

### ISSUE THREAD

**Issue by ddewaele** [Azure/azure-iot-arduino#64]
I noticed some links in the README that are broken:

- Setup your IoT hub
- Provision your device and get its credentials

It also wasn't immediately clear to me that I needed to

* update my wifi firmware on the mkr1000 to the latest version in order to get the sample to work
* install the ssl certificate from my iot hub on the mkr1000 (I noticed some instructions in another github repo but not in this one : https://github.com/Azure/azure-iot-device-ecosystem/blob/master/get_started/arduinoide-arduino-wifi101-c.md#Step-1-Prerequisites)
* It was also unclear what device connection string should be used : 

When I pasted the one from the azure portal it didn't work
```
static const char* connectionString = "HostName=xxxx.azure-devices.net;DeviceId=arduino-mkr1000;SharedAccessKey=xxxxx";
```
When creating a SAS token for my device (`iothub-explorer sas-token`), and using that in the connection string it worked
```
static const char* connectionString = "HostName=xxxx.azure-devices.net;CredentialType=SharedAccessSignature;DeviceId=arduino-mkr1000;SharedAccessSignature=SharedAccessSignature sr=xxxx.azure-devices.net%2Fdevices%2Farduino-mkr1000&sig=xxxx&se=1503763760";
```

However, these SAS tokens expire after one hour and it's not immediately clear to me how to get them refreshed from the mkr1000.

Should the sample work with a regular connection string (without the sas token) also ?

**Comment by JetstreamRoySprowl** [comment]
@ddewaele : Thanks for the report. The broken links in the Arduino libraries have been checked into master and will be fixed in the next Arduino release cycle in a week or so. 

For the other issues I'll tag @iluican, who owns the mkr1000 repo you refer to.
