### ISSUE TITLE
minimum hardware(RAM) requirements for azure-iot-arduino

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/azure-iot-arduino#67]
Azure-iot-sdk-c specified minimum of 64KB RAM as minimum hardware.  Arduino-Zero which is a supported hardware for azure-iot-arduino has only 32KB of RAM. 

1. Is the hardware requirement of this library same as azure-iot-sdk-c?
2. Is there a requirement on how much flash memory is needed for azure-iot-arduino?

I would like to know if it possible to run this SDK on ATtiny1634([link](http://www.microchip.com/wwwproducts/en/ATtiny1634)) which has just 1KB of RAM.

**Comment by mamokarz** [comment]
Hi @kiranpradeep,

Thanks have you interested in the Azure SDK. 64KB of RAM is an estimated value, but it can totally change depending on the hardware platform, the RTOS and the Stack TCP/IP+SSL that you are using. 

That said, 1KB of RAM is, for sure, not enough, the SSL layer itself will probably need much more than it, and you cannot connect to the IotHub without this security layer. 

Please consider a bigger microcontroller, you can find more hardware options at the [Azure IoT Suite](https://catalog.azureiotsuite.com/)
