### ISSUE TITLE
Can a new build be created?

### ISSUE THREAD

**Issue by Tintin4000** [Azure/azure-iot-arduino#68]
I am affected by an issue on receiving Twin which seems to have been fixed in the sdk back in August by @markrad, but the build on the Arduino library is much older.  Thanks you
P.S. I am new to GitHub and didn't know where to post this other than in the issue section.

**Comment by rcarmo** [comment]
I'd like to second this. I'm coming across stuff that might well be the result of an outdated build inside the Arduino libraries.

**Comment by Tintin4000** [comment]
Hi @rcarmo, 15 days ago a new build has been made which seems to fix my issues.

**Comment by JetstreamRoySprowl** [comment]
Yes, the Arduino libraries had gotten out-of-date for various interlocking reasons. We've streamlined the Arduino release procedure, and future updates will be much more graceful. The new 1.0.40 libraries have all the very latest code.
