### ISSUE TITLE
Is MQTT-over-WebSockets supported?

### ISSUE THREAD

**Issue by ChristianWeyer** [Azure/azure-iot-arduino#69]
Hi all,

is MQTT-over-WS supported for Arduino, something like this:
`iotHubClientHandle = IoTHubClient_LL_CreateFromConnectionString(connectionString, MQTT_WebSocket_Protocol);`

Thanks!

**Comment by JetstreamRoySprowl** [comment]
@ChristianWeyer : This is not something we have tested yet, but we will be working on it in the near future.

**Comment by cocowalla** [comment]
Hi, also interested in MQTT-over-WS, but this issue seems to have been closed without comment?

I believe .NET Core 2.1 will support websockets, so was wondering if any work had been done here to support it?

**Comment by JetstreamRoySprowl** [comment]
Hi @cocowalla , MQTT-over-WS is fully supported in our C and .NET SDKs, but the Arduino libraries are a deliberately smaller subset of the main SDK. We have no current plans to expand the existing Arduino library capabilities.

**Comment by sukretniy** [comment]
Does anyone found some warkaround to use MQTT-over-WS for aeduino? Or tried to implement MQTT_WebSocket_Protocol?

**Comment by sukretniy** [comment]
Does anyone found some workaround to use MQTT-over-WS for arduino with esp8266? Or tried to implement MQTT_WebSocket_Protocol?
