### ISSUE TITLE
Compilation cannot pass

### ISSUE THREAD

**Issue by L-eeX** [Azure/azure-iot-arduino#71]
## Hello : I am currently working on an azure-iot project, I downloaded the arduino library (https://github.com/azure/azure-iot-arduino),But compilation cannot pass.

```
D:\Arduino\libraries\azure-iot-arduino\src/AzureIoTHub.h:7:29: fatal error: AzureIoTUtility.h: No such file or directory
 #include "AzureIoTUtility.h"
```
This is the error message for the compile prompt, and there is no "AzureIoTUtility. H" file,Hope can help me solve this problem. Thank you!!!

**Comment by JetstreamRoySprowl** [comment]
@L-eeX : You missed the [Prerequisites Step](https://github.com/azure/azure-iot-arduino#prerequisites) which says to install the AzureIoTUtility library. Make sure you've installed all the required libraries and you should be okay.
