### ISSUE TITLE
SAS Token problem

### ISSUE THREAD

**Issue by KoRba88** [Azure/azure-iot-arduino#74]
Hi

My code compiled but from serial monitor i have get this messeges

Func:Base64_Decoder Line:201 Invalid length Base64 string!
Func:construct_sas_token Line:217 Unable to decode the key for generating the SAS.
Func:IoTHubClient_Auth_Get_SasToken Line:388 Failed creating sas_token
Func:SendMqttConnectMsg Line:1696 failure getting sas token from IoTHubClient_Auth_Get_SasToken.

Info: Sending sensor value Temperature = 32, Humidity = 19

Info: IoTHubClient accepted the message for delivery

And its repeating

Also I see is that nothing  appears in my IoTHub.

I have double checked the Hostname, Device Id & Device Key and they are OK.

Whats wrong?

Best Regards
KoRba88

**Comment by satyak5** [comment]
just login to the portal using incognito window because its just some cache problem . And also log out from all other browsers

**Comment by JetstreamRoySprowl** [comment]
That complaint is pointing strongly at an incorrectly formatted connection string. Have you gotten it to work yet?

**Comment by Tathagatd96** [comment]
Did you find a solution to this problem. I am facing the same issue and cannot get it to work.

Thanks for the help

**Comment by Tathagatd96** [comment]
I am directly copying the connection string from my azure portal, it's still throwing me an error. Do we have to copy in the entire string or just the shared access part?

**Comment by satyak5** [comment]
I am really sorry bruh !I forgot actually.  i used to work on that a year
back and now i am into web development. I wish i could have helped you.
Copy connection string from device explorer. That will work i guess

**Comment by foote** [comment]
Anyone come up with a solution for this?
2019-05-20 01:06:56 ERROR: base64_utility.c (ln 201): Invalid length Base64 string!
2019-05-20 01:06:56 ERROR: sastoken.c (ln 217): Unable to decode the key for generating the SAS.
2019-05-20 01:06:56 ERROR: iothub_client_authorization.c (ln 460): Failed creating sas_token
2019-05-20 01:06:56 ERROR: iothubtransport_mqtt_common.c (ln 2169): failure getting sas token from IoTHubClient_Auth_Get_SasToken.

**Comment by jbobotek** [comment]
This issue has not received any responses for quite some time. Closing. If you continue to experience issues, please open a new issue.
