### ISSUE TITLE
Issue with strftime when using include azureiothub?

### ISSUE THREAD

**Issue by Tintin4000** [Azure/azure-iot-arduino#78]
Can a new azure arduino library be compiled with the latest one of Microsoft?

**Comment by Tintin4000** [comment]
I found that in the azureiotutility there is a time.cpp that include:
   size_t strftime(char *s, size_t maxsize, const char* format, const struct tm *timeptr)
    {
        /*For now esp8266 will not report time.*/
        (void)(s, maxsize, format, timeptr);        
        return 0;
    }
Can this be fixed or enhanced?

**Comment by ewertons** [comment]
Hi @Tintin4000 ,
let me get more details on this and I'll reply soon.

**Comment by Tintin4000** [comment]
I am using the strftime function to format the time which started to return an empty string after referring the #include <AzureIoTHub.h> in the code.  As posted before, I found out that the reason was that the function gets overwritten by the AzureIoTUtility (Azure/azure-iot-pal-arduino) under the esp8266 as per my earlier comment.  I don't know why it is so and if it can be changed.  I have for now simply comment the function in the time.cpp file. and everything seems ok.

**Comment by JetstreamRoySprowl** [comment]
@Tintin4000 : We've just pushed version 1.0.45 out which fixes this. That time.c file has been deleted because the recent versions of the ESP8266 library implement those functions
