### ISSUE TITLE
RAM issue

### ISSUE THREAD

**Issue by sukretniy** [Azure/azure-iot-arduino#80]
1.0.45 version uses more RAM and more space then 1.0.44 on esp8266

My project with 1.0.45 uses 
559565 bytes (54%) from total of 1023984 space 
52112 bytes (63%) leaving free 29808 from 81920 of RAM

My project with 1.0.44 uses 
550661 bytes (53%) from total of 1023984 space 
49552 bytes (60%) leaving free 32368 from 81920 of RAM

**Comment by jbobotek** [comment]
RAM usage may vary from version to version.
