### ISSUE TITLE
Device Disconnects from IOT Hub after 1 hr

### ISSUE THREAD

**Issue by jagpreetstamber** [Azure/azure-iot-arduino#85]
I am using ESP8266 device with device twins over MQTT protocol.

I am sending the reported state using IoTHubClient_LL_SendReportedState, Also registered call back for desired properties.

Everything works fine till approx 1 hr, then the device disconnects from IOT hub, It does not receive the changes in desired state, also it does not send the reported properties. No failure comes on device while sending the reported properties, but nothing happens.

I am calling IoTHubClient_LL_DoWork every 100 ms

**Comment by jbobotek** [comment]
Please try the latest libs. Let us know if your problem still persists!
