### ISSUE TITLE
How to connect ESP8266 with "Auto Device Provisioning Service" to Azure cloud

### ISSUE THREAD

**Issue by iotics** [Azure/azure-iot-arduino#87]
Hello, I am facing issue in connecting my ESP8266[NodeMCU] to Azure Cloud by "Auto Device Provisioning Service" method. For that I went through so many microsoft azure dps docs. But I got links for MXchip IOT devkit and ESP32, no official link available for esp8266. My esp8266 allowed me to successfully upload .ino code with connection string (copied from Linked IoT hub details in DeviceProvisioningService).  After upload, I can't find any new IOT device created by AutoDPS in IOT devices explorer. I have also included rootCA certificate in data folder via SPIFFS. My doubts are, am I supposed to use any other connection string or should I upload .ino file without connection string...? Where should I put "ID Scope" in my .ino file for esp8266..? If anyone have any other method to do the same task, please share with me. Thanks in advance.

**Comment by jbobotek** [comment]
There is currently no sample nor included functions to enable DPS with either ESP board using our released Arduino libraries. If you would like to try to make it work, I would suggest adapting [this sample](https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_client/samples/prov_dev_client_ll_sample/prov_dev_client_ll_sample.c) for use with our Arduino libraries.

**Comment by Misiu** [comment]
@iotics did you succeed with that?
I'm also searching for an easy way to connect multiple devices to IoT Hub using DPS.
@jbobotek I think not only we two are searching for such functionality.

My use case is simple: at the first run of the device, it will create an access point, the user will add his wifi credentials and his unique id, this should be passed to DPS and the device should show up in IoT Hub.

I think that a proper sample will be very helpful. ESP boards are still very common.
