### ISSUE TITLE
Newer version of ESP8266 Plataform

### ISSUE THREAD

**Issue by mtolent** [Azure/azure-iot-arduino#92]
Hi,

Is there an update of the SDK for newer versions of Arduino IDE?

In fact, I'm using PlatformIO with Visual Studio Code and I have to select an old 1.8.0 version of the ESP 8266 plataform for the code to compile. (I just assume if there is a version for newest Arduino IDE it should be ok for lastear PlatformIO as well).

What's in truly bothering me is the tons of warnings I get when compiling. I realy can't tell if there is something I should be worried or not.

Thanks!

**Comment by jbobotek** [comment]
I have been testing with 1.8.10 with no compile errors, what warnings are you getting? (I wouldn't be concerned over warnings as a root case however.)
