### ISSUE TITLE
Replacement for this repository functionality

### ISSUE THREAD

**Issue by grassgit** [Azure/azure-iot-arduino#96]
Visual Studio code includes a complete example covering most of this functionality in a few clear steps. 
Please add this to the readme as a simpler alternative for the expressif version.

https://docs.microsoft.com/en-us/samples/azure-samples/esp32-iot-devkit-get-started/sample/

**Comment by jbobotek** [comment]
Yet to try that personally, have you verified it works?

**Comment by anmenaga** [comment]
Yes, it works.
Though I wouldn't call it `few clear steps`. That link:
* is for ESP32 only; this doc also has example for ESP8266
* adds yet another tool (VS Code) required for build.

In any case it would be good to have reference to that guide in this repo.

**Comment by jbobotek** [comment]
Ok, so that sample is without the Arduino ecosystem, so in that sense, it's a separate implementation.
